version: '3.8'

networks:

  default:
    driver: bridge
    name: rinha-2024-q1
    
services:

  postgres:
    container_name: postgres
    hostname: postgres
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/vars.env
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: '250MB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  api01:
    container_name: api01
    hostname: api01
    build: 
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100MB' 

  api02:
    container_name: api02
    hostname: api02
    build: 
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100MB'    

  nginx:
    container_name: nginx
    hostname: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      api01:
        condition: service_healthy 
      api02:
        condition: service_healthy           
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '100MB'

