CREATE TABLE IF NOT EXISTS clientes (
  id SERIAL PRIMARY KEY,
  limite INTEGER NOT NULL,
  saldo INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS transacoes (
  id SERIAL PRIMARY KEY,  
  client_id INTEGER NOT NULL REFERENCES clientes(id),
  valor INTEGER NOT NULL,
  tipo VARCHAR(1) NOT NULL CHECK (tipo IN ('c', 'd')),
  descricao VARCHAR(10),
  data TIMESTAMPTZ DEFAULT (NOW())
);


INSERT INTO clientes VALUES (1,   100000, 0);
INSERT INTO clientes VALUES (2,    80000, 0);
INSERT INTO clientes VALUES (3,  1000000, 0);
INSERT INTO clientes VALUES (4, 10000000, 0);
INSERT INTO clientes VALUES (5,   500000, 0);

