FROM docker.io/postgres:15.6

COPY config.sql /docker-entrypoint-initdb.d/config.sql
COPY create-table-2.sql /docker-entrypoint-initdb.d/create-table-2.sql
COPY init-table-2.sql /docker-entrypoint-initdb.d/init-table-2.sql
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d/

